.\" Manpage for astroTools.
.\" Contact AstroFloyd at astrofloyd.org to correct errors or typos.
.TH "astroTools" 1 "Sun Jun 21 2015" "astroTools"
.ad l
.nh
.SH NAME
astroTools \- command-line tools for astronomy and astrophysics, written in Fortran

.SH DESCRIPTION

The package astroTools provides assorted command-line tools for astronomy and 
astrophysics, written in Fortran. The package is currently in the alpha stage; 
many programs sit around on my computer, waiting to be gathered, tidied up and 
added — stay tuned.  They can be used under the 
conditions of version 3 of the GPL.  To download the astroTools package, read the 
code documentation, or to contact the developer, see: 
\fBhttp://astrotools.sourceforge.net\fP\&.

.SH SYNOPSIS
\fBat_<command>\fP \fI[<options>]\fP

.PP
.SS "Commands"
.br

.RI "\fBat_arcsec2deg_rad\fP  Convert an angle expressed in arcseconds to degrees and radians"

.RI "\fBat_cal2gps\fP  Convert a calendar date/time to GPS time"

.RI "\fBat_cal2jd\fP  Compute the Julian day for a given calendar date"

.RI "\fBat_cal2times\fP  Convert a calendar date/time from the system clock or command line to a number of date/time formats"

.RI "\fBat_cal2unix\fP  Convert a calendar date/time to a Unix time stamp "

.RI "\fBat_comet_eq2ap\fP  Calculate the semi-majro axis \fIa\fP and orbital period \fIP\fP of a comet from its eccentricity \fIe\fP and perihelion distance \fIq\fP"

.RI "\fBat_dd2dms_rad\fP  Convert an angle expressed in decimal degrees to degrees and arcminutes, degrees, arcminutes and arcseconds, and radians"

.RI "\fBat_dms2dd_rad\fP  Convert an angle expressed in degrees, arcminutes and arcseconds to decimal degrees and radians"

.RI "\fBat_eq2hor\fP  Convert equatorial coordinates (\fIRA\fP, \fIdec\fP) to horizontal (\fIaz\fP, \fIalt\fP)"

.RI "\fBat_gps2cal\fP  Convert GPS time to calendar date and time"

.RI "\fBat_jd2cal\fP  Compute the calendar date, time and GMST for a given Julian day"

.RI "\fBat_jd2times\fP  Convert a Julian day to a number of date/time formats"

.RI "\fBat_rad2dd_dms\fP  Convert an angle expressed in radians to decimal degrees, degrees and arcminutes, and degrees, arcminutes and arcseconds"

.RI "\fBat_rect2spher\fP  Convert rectangular coordinates to spherical coordinates"

.RI "\fBat_settings\fP  Print the current settings and optionally create a new settings file.  \fI--create\fP  prints the current settings and asks a few questions to create a new settings file, overwriting the old one"

.RI "\fBat_unix2cal\fP  Convert a Unix time stamp to a calendar date/time"



.SH "AUTHOR"
.PP 
astroTools was written by AstroFloyd (\fBhttp://astrofloyd.org\fP)\&
